import type { Metadata } from "next";
import { Geist, Great_Vibes, Lato } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Molecoles/Navbar/Navbar"

const great_vibes = Great_Vibes({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-great_vibes",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lato_font = Lato({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-lato",
})

export const metadata: Metadata = {
  title: "Samuele Gennaro",
  description: "Generated by create next app",
  icons: "/icon.jpeg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="it">
      <body
        className={`${geistSans.variable} ${lato_font.variable} ${great_vibes.variable} antialiased`}
      >
        <Navbar/>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
